/**
 * Subset Noto Sans TC down to the characters this site actually uses.
 *
 * Why this exists
 * ---------------
 * Pre-sliced CJK webfonts (Fontsource, Google Fonts' unicode-range CSS) split
 * the font into ~105 files so a page downloads only the slices it needs. That
 * works well for character-heavy sites. It works badly here: the Chinese pages
 * are short, but their characters are scattered across slices 107–119, so the
 * browser fetched 14 files totalling 936 KB and first contentful paint landed
 * at 4.7 s. Measured, not assumed — see the Phase 1 notes in README.md.
 *
 * This site has ~365 distinct Chinese characters in total, so subsetting to the
 * real character set collapses that into one request per weight.
 *
 * The character set is derived from the sources at build time, so adding
 * Chinese copy anywhere under src/ is picked up on the next build. Nothing has
 * to be maintained by hand. If a character somehow escapes the scan the page
 * still renders — it falls back to the system CJK font rather than breaking.
 */
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { join, extname, relative } from "node:path";
import { fileURLToPath } from "node:url";
import subsetFont from "subset-font";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

/** Directories scanned for text that will be rendered. */
const SCAN_DIRS = [
  "src/content",
  "src/pages",
  "src/components",
  "src/layouts",
  "src/i18n",
];

/** Files at the project root that carry rendered copy. */
const SCAN_FILES = ["astro-paper.config.ts"];

const SCAN_EXTENSIONS = new Set([".md", ".mdx", ".astro", ".ts", ".tsx"]);

/** Not routed, not rendered — Phase 5 blog surfaces. */
const IGNORED = ["src/parked"];

/**
 * Always included regardless of current copy, so small edits do not silently
 * drop a glyph: ASCII, the CJK punctuation used in Chinese typesetting, and
 * full-width forms.
 */
const BASELINE = [
  // Printable ASCII
  ...Array.from({ length: 95 }, (_, i) => String.fromCodePoint(32 + i)),
  // CJK and general punctuation
  "、。〈〉《》「」『』【】〔〕・…‥—–‐‘’“”′″〜～",
  "！＂＃＄％＆＇（）＊＋，－．／：；＜＝＞？＠［＼］＾＿｀｛｜｝",
  "©®°±×÷§¶†‡•→←↑↓⋯",
].join("");

async function* walk(dir) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    const rel = relative(ROOT, full).replace(/\\/g, "/");
    if (IGNORED.some(ignored => rel.startsWith(ignored))) continue;
    if (entry.isDirectory()) yield* walk(full);
    else if (SCAN_EXTENSIONS.has(extname(entry.name))) yield full;
  }
}

async function collectCharacters() {
  const chars = new Set(BASELINE);

  const files = [];
  for (const dir of SCAN_DIRS) {
    for await (const file of walk(join(ROOT, dir))) files.push(file);
  }
  for (const file of SCAN_FILES) files.push(join(ROOT, file));

  for (const file of files) {
    let contents;
    try {
      contents = await readFile(file, "utf8");
    } catch {
      continue;
    }
    for (const ch of contents) chars.add(ch);
  }

  return { text: [...chars].join(""), fileCount: files.length };
}

const WEIGHTS = [
  {
    weight: 400,
    source: "@expo-google-fonts/noto-sans-tc/400Regular/NotoSansTC_400Regular.ttf",
    out: "noto-sans-tc-400.subset.woff2",
  },
  {
    weight: 700,
    source: "@expo-google-fonts/noto-sans-tc/700Bold/NotoSansTC_700Bold.ttf",
    out: "noto-sans-tc-700.subset.woff2",
  },
];

const OUT_DIR = join(ROOT, "src/assets/fonts");
const CSS_PATH = join(ROOT, "src/styles/fonts.generated.css");

const { text, fileCount } = await collectCharacters();
const cjkCount = [...text].filter(ch => {
  const cp = ch.codePointAt(0);
  return cp >= 0x3400 && cp <= 0x9fff;
}).length;

await mkdir(OUT_DIR, { recursive: true });

const faces = [];
for (const { weight, source, out } of WEIGHTS) {
  const sourcePath = join(ROOT, "node_modules", source);
  const original = await readFile(sourcePath);
  const subset = await subsetFont(original, text, { targetFormat: "woff2" });
  await writeFile(join(OUT_DIR, out), subset);

  const saved = (1 - subset.length / original.length) * 100;
  console.log(
    `  ${weight}: ${(original.length / 1024 / 1024).toFixed(1)} MB -> ` +
      `${(subset.length / 1024).toFixed(1)} KB (-${saved.toFixed(2)}%)`
  );

  faces.push(`@font-face {
  font-family: "Noto Sans TC";
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url("../assets/fonts/${out}") format("woff2");
}`);
}

const header = `/* GENERATED by scripts/build-fonts.mjs — do not edit by hand.
 *
 * Noto Sans TC subset to the ${cjkCount} CJK characters (plus Latin and
 * punctuation) found across ${fileCount} source files. Regenerated on every
 * build, so new Chinese copy is covered automatically.
 *
 * Noto Sans TC is licensed under the SIL Open Font License 1.1.
 */
`;

await writeFile(CSS_PATH, `${header}\n${faces.join("\n\n")}\n`);

console.log(
  `  character set: ${[...text].length} total, ${cjkCount} CJK, from ${fileCount} files`
);
